In [21]:
import pandas as pd
import numpy as np
import xml.etree.ElementTree as ET


# Parse XML
tree = ET.parse("data/cante2midi_meta.xml")   # or ET.fromstring(xml_string)
root = tree.getroot()

rows = []

for track in root.findall("track"):
    row = {}
    
    row["id"] = track.get("id")
    
    source = track.find("source")
    row["anthology"] = source.findtext("anthology")
    row["cd_no"] = source.findtext("cd-no")
    row["track_no"] = source.findtext("track-no")
    
    meta = track.find("meta")
    row["artist"] = meta.findtext("artist")
    row["title"] = meta.findtext("title")
    row["style"] = meta.findtext("style")
    row["duration_min"] = meta.findtext("duration_min")
    row["duration_sec"] = meta.findtext("duration_sec")
    
    row["musicBrainz"] = track.findtext("musicBrainz")
    
    rows.append(row)

cante2midi_meta = pd.DataFrame(rows)


cante2midi_meta['id']=cante2midi_meta['id'].astype('Int64')
cante2midi_meta.head()

,id,anthology,cd_no,track_no,artist,title,style,duration_min,duration_sec,musicBrainz
0,1,Magna antología del cante flamenco,6,6,Gabriel Moreno,Yo no te dao motivos,Tiento de La Niña de los Peines,4,8,f1e14261-4e57-485a-a8f3-87892f19b4c4
1,2,Magna antología del cante flamenco,8,8,Bernardo el de los lobitos,Los peces mueran de pena,Malagueña de Gayarrito,3,10,a7772f17-6b79-485f-a61c-7a224c90191c
2,3,Magna antología del cante flamenco,7,15,Bernardo el de los lobitos,Por las trenzas de tu pelo,Malagueñita de El Canario,3,15,dc6a38ce-a357-4f3a-a853-5b85f9b8fe6f
3,4,Magna antología del cante flamenco,5,17,Angel de Alora,Los caminos estan muy malos,Cantes del piyayo (Tango de Málaga),3,10,e8863f01-8cfb-4a22-b070-65cfa44c0e6c
4,5,Magna antología del cante flamenco,2,17,Antonio Mairena,Verguenza,Siguiriyas de Cadiz,1,46,ab797c04-6764-4c71-86fd-a3cdfbd98975

In [26]:
from pathlib import Path

folder = Path("/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mir/data/cante2midiaudio")
wav_files = list(folder.glob("*.wav"))

ids = [int(file.name.split('_')[0]) for file in wav_files]
folder = Path("/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mir/data/cante2midi_f0")
f0_files = list(folder.glob("*.csv"))

path_df = pd.DataFrame(
    {'id': ids,
     'wav_path': wav_files,
     'f0_path': f0_files,
    })

path_df.head()

,id,wav_path,f0_path
0,15,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...
1,8,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...
2,5,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...
3,18,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...
4,19,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...,/home/ibroto/Documents/UPF_SMC/MIR/flamenco-mi...

In [28]:
merged_df = cante2midi_meta.merge(path_df, on='id')
merged_df.to_csv('wav_f0_paths_mapping.csv', index=False)